// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: networks/networks.proto

package pb_networks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkType int32

const (
	NetworkType_NT_EVM    NetworkType = 0
	NetworkType_NT_CASPER NetworkType = 1
	NetworkType_NT_SOLANA NetworkType = 2
)

// Enum value maps for NetworkType.
var (
	NetworkType_name = map[int32]string{
		0: "NT_EVM",
		1: "NT_CASPER",
		2: "NT_SOLANA",
	}
	NetworkType_value = map[string]int32{
		"NT_EVM":    0,
		"NT_CASPER": 1,
		"NT_SOLANA": 2,
	}
)

func (x NetworkType) Enum() *NetworkType {
	p := new(NetworkType)
	*p = x
	return p
}

func (x NetworkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkType) Descriptor() protoreflect.EnumDescriptor {
	return file_networks_networks_proto_enumTypes[0].Descriptor()
}

func (NetworkType) Type() protoreflect.EnumType {
	return &file_networks_networks_proto_enumTypes[0]
}

func (x NetworkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkType.Descriptor instead.
func (NetworkType) EnumDescriptor() ([]byte, []int) {
	return file_networks_networks_proto_rawDescGZIP(), []int{0}
}

type ConnectedNetworksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Networks []*ConnectedNetworksResponse_Network `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
}

func (x *ConnectedNetworksResponse) Reset() {
	*x = ConnectedNetworksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_networks_networks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectedNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedNetworksResponse) ProtoMessage() {}

func (x *ConnectedNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networks_networks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedNetworksResponse.ProtoReflect.Descriptor instead.
func (*ConnectedNetworksResponse) Descriptor() ([]byte, []int) {
	return file_networks_networks_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectedNetworksResponse) GetNetworks() []*ConnectedNetworksResponse_Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

type SupportedTokensRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkId uint32 `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
}

func (x *SupportedTokensRequest) Reset() {
	*x = SupportedTokensRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_networks_networks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedTokensRequest) ProtoMessage() {}

func (x *SupportedTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networks_networks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedTokensRequest.ProtoReflect.Descriptor instead.
func (*SupportedTokensRequest) Descriptor() ([]byte, []int) {
	return file_networks_networks_proto_rawDescGZIP(), []int{1}
}

func (x *SupportedTokensRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

type TokensResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokens []*TokensResponse_Token `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *TokensResponse) Reset() {
	*x = TokensResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_networks_networks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensResponse) ProtoMessage() {}

func (x *TokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networks_networks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensResponse.ProtoReflect.Descriptor instead.
func (*TokensResponse) Descriptor() ([]byte, []int) {
	return file_networks_networks_proto_rawDescGZIP(), []int{2}
}

func (x *TokensResponse) GetTokens() []*TokensResponse_Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type ConnectedNetworksResponse_Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type      NetworkType `protobuf:"varint,3,opt,name=type,proto3,enum=golden_gate.NetworkType" json:"type,omitempty"`
	IsTestnet bool        `protobuf:"varint,4,opt,name=is_testnet,json=isTestnet,proto3" json:"is_testnet,omitempty"`
}

func (x *ConnectedNetworksResponse_Network) Reset() {
	*x = ConnectedNetworksResponse_Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_networks_networks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectedNetworksResponse_Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedNetworksResponse_Network) ProtoMessage() {}

func (x *ConnectedNetworksResponse_Network) ProtoReflect() protoreflect.Message {
	mi := &file_networks_networks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedNetworksResponse_Network.ProtoReflect.Descriptor instead.
func (*ConnectedNetworksResponse_Network) Descriptor() ([]byte, []int) {
	return file_networks_networks_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConnectedNetworksResponse_Network) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectedNetworksResponse_Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectedNetworksResponse_Network) GetType() NetworkType {
	if x != nil {
		return x.Type
	}
	return NetworkType_NT_EVM
}

func (x *ConnectedNetworksResponse_Network) GetIsTestnet() bool {
	if x != nil {
		return x.IsTestnet
	}
	return false
}

type TokensResponse_TokenAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkId uint32 `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Decimals  uint32 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
}

func (x *TokensResponse_TokenAddress) Reset() {
	*x = TokensResponse_TokenAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_networks_networks_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokensResponse_TokenAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensResponse_TokenAddress) ProtoMessage() {}

func (x *TokensResponse_TokenAddress) ProtoReflect() protoreflect.Message {
	mi := &file_networks_networks_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensResponse_TokenAddress.ProtoReflect.Descriptor instead.
func (*TokensResponse_TokenAddress) Descriptor() ([]byte, []int) {
	return file_networks_networks_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TokensResponse_TokenAddress) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *TokensResponse_TokenAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TokensResponse_TokenAddress) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

type TokensResponse_Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32                         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortName string                         `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	LongName  string                         `protobuf:"bytes,3,opt,name=long_name,json=longName,proto3" json:"long_name,omitempty"`
	Addresses []*TokensResponse_TokenAddress `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *TokensResponse_Token) Reset() {
	*x = TokensResponse_Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_networks_networks_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokensResponse_Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensResponse_Token) ProtoMessage() {}

func (x *TokensResponse_Token) ProtoReflect() protoreflect.Message {
	mi := &file_networks_networks_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensResponse_Token.ProtoReflect.Descriptor instead.
func (*TokensResponse_Token) Descriptor() ([]byte, []int) {
	return file_networks_networks_proto_rawDescGZIP(), []int{2, 1}
}

func (x *TokensResponse_Token) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TokensResponse_Token) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *TokensResponse_Token) GetLongName() string {
	if x != nil {
		return x.LongName
	}
	return ""
}

func (x *TokensResponse_Token) GetAddresses() []*TokensResponse_TokenAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_networks_networks_proto protoreflect.FileDescriptor

var file_networks_networks_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x6f, 0x6c, 0x64, 0x65,
	0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x22, 0xe3, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f,
	0x67, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x08, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x1a, 0x7a, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x69, 0x73, 0x54, 0x65, 0x73, 0x74, 0x6e, 0x65, 0x74, 0x22, 0x37, 0x0a, 0x16,
	0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x64, 0x22, 0xce, 0x02, 0x0a, 0x0e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65,
	0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x06, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x1a, 0x63, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x1a, 0x9b, 0x01, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x46,
	0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x09, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x2a, 0x37, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x54, 0x5f, 0x45, 0x56, 0x4d, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x54, 0x5f, 0x43, 0x41, 0x53, 0x50, 0x45, 0x52, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x54, 0x5f, 0x53, 0x4f, 0x4c, 0x41, 0x4e, 0x41, 0x10, 0x02, 0x42,
	0x5a, 0x5a, 0x58, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x6f,
	0x6f, 0x73, 0x74, 0x79, 0x4c, 0x61, 0x62, 0x73, 0x2f, 0x63, 0x61, 0x73, 0x70, 0x65, 0x72, 0x2d,
	0x65, 0x74, 0x68, 0x2d, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2f, 0x62, 0x6f, 0x6f, 0x73, 0x74,
	0x79, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x3b,
	0x70, 0x62, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_networks_networks_proto_rawDescOnce sync.Once
	file_networks_networks_proto_rawDescData = file_networks_networks_proto_rawDesc
)

func file_networks_networks_proto_rawDescGZIP() []byte {
	file_networks_networks_proto_rawDescOnce.Do(func() {
		file_networks_networks_proto_rawDescData = protoimpl.X.CompressGZIP(file_networks_networks_proto_rawDescData)
	})
	return file_networks_networks_proto_rawDescData
}

var file_networks_networks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_networks_networks_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_networks_networks_proto_goTypes = []interface{}{
	(NetworkType)(0),                          // 0: golden_gate.NetworkType
	(*ConnectedNetworksResponse)(nil),         // 1: golden_gate.ConnectedNetworksResponse
	(*SupportedTokensRequest)(nil),            // 2: golden_gate.SupportedTokensRequest
	(*TokensResponse)(nil),                    // 3: golden_gate.TokensResponse
	(*ConnectedNetworksResponse_Network)(nil), // 4: golden_gate.ConnectedNetworksResponse.Network
	(*TokensResponse_TokenAddress)(nil),       // 5: golden_gate.TokensResponse.TokenAddress
	(*TokensResponse_Token)(nil),              // 6: golden_gate.TokensResponse.Token
}
var file_networks_networks_proto_depIdxs = []int32{
	4, // 0: golden_gate.ConnectedNetworksResponse.networks:type_name -> golden_gate.ConnectedNetworksResponse.Network
	6, // 1: golden_gate.TokensResponse.tokens:type_name -> golden_gate.TokensResponse.Token
	0, // 2: golden_gate.ConnectedNetworksResponse.Network.type:type_name -> golden_gate.NetworkType
	5, // 3: golden_gate.TokensResponse.Token.addresses:type_name -> golden_gate.TokensResponse.TokenAddress
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_networks_networks_proto_init() }
func file_networks_networks_proto_init() {
	if File_networks_networks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_networks_networks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectedNetworksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_networks_networks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedTokensRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_networks_networks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokensResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_networks_networks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectedNetworksResponse_Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_networks_networks_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokensResponse_TokenAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_networks_networks_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokensResponse_Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_networks_networks_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networks_networks_proto_goTypes,
		DependencyIndexes: file_networks_networks_proto_depIdxs,
		EnumInfos:         file_networks_networks_proto_enumTypes,
		MessageInfos:      file_networks_networks_proto_msgTypes,
	}.Build()
	File_networks_networks_proto = out.File
	file_networks_networks_proto_rawDesc = nil
	file_networks_networks_proto_goTypes = nil
	file_networks_networks_proto_depIdxs = nil
}
