// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: connector/connector.proto

package pb_connector

import (
	transfers "github.com/BoostyLabs/casper-eth-bridge/boosty-communication/go-gen/transfers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type StringAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *StringAddress) Reset() {
	*x = StringAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringAddress) ProtoMessage() {}

func (x *StringAddress) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringAddress.ProtoReflect.Descriptor instead.
func (*StringAddress) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{1}
}

func (x *StringAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNumber *uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{2}
}

func (x *EventsRequest) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//	*Event_FundsIn
	//	*Event_FundsOut
	Variant isEvent_Variant `protobuf_oneof:"variant"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{3}
}

func (m *Event) GetVariant() isEvent_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *Event) GetFundsIn() *EventFundsIn {
	if x, ok := x.GetVariant().(*Event_FundsIn); ok {
		return x.FundsIn
	}
	return nil
}

func (x *Event) GetFundsOut() *EventFundsOut {
	if x, ok := x.GetVariant().(*Event_FundsOut); ok {
		return x.FundsOut
	}
	return nil
}

type isEvent_Variant interface {
	isEvent_Variant()
}

type Event_FundsIn struct {
	FundsIn *EventFundsIn `protobuf:"bytes,1,opt,name=funds_in,json=fundsIn,proto3,oneof"`
}

type Event_FundsOut struct {
	FundsOut *EventFundsOut `protobuf:"bytes,2,opt,name=funds_out,json=fundsOut,proto3,oneof"`
}

func (*Event_FundsIn) isEvent_Variant() {}

func (*Event_FundsOut) isEvent_Variant() {}

type EventFundsIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From   *Address                        `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To     *transfers.StringNetworkAddress `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount string                          `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Token  *Address                        `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Tx     *TransactionInfo                `protobuf:"bytes,5,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *EventFundsIn) Reset() {
	*x = EventFundsIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFundsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFundsIn) ProtoMessage() {}

func (x *EventFundsIn) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFundsIn.ProtoReflect.Descriptor instead.
func (*EventFundsIn) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{4}
}

func (x *EventFundsIn) GetFrom() *Address {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EventFundsIn) GetTo() *transfers.StringNetworkAddress {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EventFundsIn) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *EventFundsIn) GetToken() *Address {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *EventFundsIn) GetTx() *TransactionInfo {
	if x != nil {
		return x.Tx
	}
	return nil
}

type EventFundsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To     *Address                        `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From   *transfers.StringNetworkAddress `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Amount string                          `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Token  *Address                        `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Tx     *TransactionInfo                `protobuf:"bytes,5,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *EventFundsOut) Reset() {
	*x = EventFundsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFundsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFundsOut) ProtoMessage() {}

func (x *EventFundsOut) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFundsOut.ProtoReflect.Descriptor instead.
func (*EventFundsOut) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{5}
}

func (x *EventFundsOut) GetTo() *Address {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EventFundsOut) GetFrom() *transfers.StringNetworkAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EventFundsOut) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *EventFundsOut) GetToken() *Address {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *EventFundsOut) GetTx() *TransactionInfo {
	if x != nil {
		return x.Tx
	}
	return nil
}

type TransactionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash        []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Blocknumber uint64 `protobuf:"varint,2,opt,name=blocknumber,proto3" json:"blocknumber,omitempty"`
	Sender      []byte `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionInfo) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *TransactionInfo) GetBlocknumber() uint64 {
	if x != nil {
		return x.Blocknumber
	}
	return 0
}

func (x *TransactionInfo) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

type ConnectorTokens struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokens []*ConnectorTokens_ConnectorToken `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *ConnectorTokens) Reset() {
	*x = ConnectorTokens{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectorTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorTokens) ProtoMessage() {}

func (x *ConnectorTokens) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorTokens.ProtoReflect.Descriptor instead.
func (*ConnectorTokens) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectorTokens) GetTokens() []*ConnectorTokens_ConnectorToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type TokenOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount        string                          `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Token         *Address                        `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	To            *Address                        `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	From          *transfers.StringNetworkAddress `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	TransactionId uint64                          `protobuf:"varint,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
}

func (x *TokenOutRequest) Reset() {
	*x = TokenOutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenOutRequest) ProtoMessage() {}

func (x *TokenOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenOutRequest.ProtoReflect.Descriptor instead.
func (*TokenOutRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{8}
}

func (x *TokenOutRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TokenOutRequest) GetToken() *Address {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TokenOutRequest) GetTo() *Address {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TokenOutRequest) GetFrom() *transfers.StringNetworkAddress {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TokenOutRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type TokenOutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txhash []byte `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
}

func (x *TokenOutResponse) Reset() {
	*x = TokenOutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenOutResponse) ProtoMessage() {}

func (x *TokenOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenOutResponse.ProtoReflect.Descriptor instead.
func (*TokenOutResponse) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{9}
}

func (x *TokenOutResponse) GetTxhash() []byte {
	if x != nil {
		return x.Txhash
	}
	return nil
}

type ConnectorTokens_ConnectorToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address *Address `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ConnectorTokens_ConnectorToken) Reset() {
	*x = ConnectorTokens_ConnectorToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_connector_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectorTokens_ConnectorToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorTokens_ConnectorToken) ProtoMessage() {}

func (x *ConnectorTokens_ConnectorToken) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorTokens_ConnectorToken.ProtoReflect.Descriptor instead.
func (*ConnectorTokens_ConnectorToken) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ConnectorTokens_ConnectorToken) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectorTokens_ConnectorToken) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_connector_connector_proto protoreflect.FileDescriptor

var file_connector_connector_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x72, 0x69,
	0x63, 0x6f, 0x72, 0x6e, 0x1a, 0x19, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x2f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x23, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x48, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x7d, 0x0a, 0x05, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x49, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x66,
	0x75, 0x6e, 0x64, 0x73, 0x49, 0x6e, 0x12, 0x35, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x5f,
	0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x72, 0x69, 0x63,
	0x6f, 0x72, 0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x4f, 0x75,
	0x74, 0x48, 0x00, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x4f, 0x75, 0x74, 0x42, 0x09, 0x0a,
	0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x22, 0xcd, 0x01, 0x0a, 0x0c, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x49, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72,
	0x6e, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12,
	0x2d, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x72,
	0x69, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x6e, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x28,
	0x0a, 0x02, 0x74, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72, 0x69,
	0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02, 0x74, 0x78, 0x22, 0xce, 0x01, 0x0a, 0x0d, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x20, 0x0a, 0x02, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x6e,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x31, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x72, 0x69,
	0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x6e,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x28, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72,
	0x69, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02, 0x74, 0x78, 0x22, 0x5f, 0x0a, 0x0f, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0xa0, 0x01, 0x0a, 0x0f, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x3f,
	0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x1a,
	0x4c, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2a, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xcd, 0x01,
	0x0a, 0x0f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f,
	0x72, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x20, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x31, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x2a, 0x0a,
	0x10, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x74, 0x78, 0x68, 0x61, 0x73, 0x68, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x6f, 0x6f, 0x73, 0x74, 0x79, 0x4c, 0x61,
	0x62, 0x73, 0x2f, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x2d, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x6f, 0x2d,
	0x67, 0x65, 0x6e, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x3b, 0x70, 0x62,
	0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_connector_connector_proto_rawDescOnce sync.Once
	file_connector_connector_proto_rawDescData = file_connector_connector_proto_rawDesc
)

func file_connector_connector_proto_rawDescGZIP() []byte {
	file_connector_connector_proto_rawDescOnce.Do(func() {
		file_connector_connector_proto_rawDescData = protoimpl.X.CompressGZIP(file_connector_connector_proto_rawDescData)
	})
	return file_connector_connector_proto_rawDescData
}

var file_connector_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_connector_connector_proto_goTypes = []interface{}{
	(*Address)(nil),                        // 0: tricorn.Address
	(*StringAddress)(nil),                  // 1: tricorn.StringAddress
	(*EventsRequest)(nil),                  // 2: tricorn.EventsRequest
	(*Event)(nil),                          // 3: tricorn.Event
	(*EventFundsIn)(nil),                   // 4: tricorn.EventFundsIn
	(*EventFundsOut)(nil),                  // 5: tricorn.EventFundsOut
	(*TransactionInfo)(nil),                // 6: tricorn.TransactionInfo
	(*ConnectorTokens)(nil),                // 7: tricorn.ConnectorTokens
	(*TokenOutRequest)(nil),                // 8: tricorn.TokenOutRequest
	(*TokenOutResponse)(nil),               // 9: tricorn.TokenOutResponse
	(*ConnectorTokens_ConnectorToken)(nil), // 10: tricorn.ConnectorTokens.ConnectorToken
	(*transfers.StringNetworkAddress)(nil), // 11: tricorn.StringNetworkAddress
}
var file_connector_connector_proto_depIdxs = []int32{
	4,  // 0: tricorn.Event.funds_in:type_name -> tricorn.EventFundsIn
	5,  // 1: tricorn.Event.funds_out:type_name -> tricorn.EventFundsOut
	0,  // 2: tricorn.EventFundsIn.from:type_name -> tricorn.Address
	11, // 3: tricorn.EventFundsIn.to:type_name -> tricorn.StringNetworkAddress
	0,  // 4: tricorn.EventFundsIn.token:type_name -> tricorn.Address
	6,  // 5: tricorn.EventFundsIn.tx:type_name -> tricorn.TransactionInfo
	0,  // 6: tricorn.EventFundsOut.to:type_name -> tricorn.Address
	11, // 7: tricorn.EventFundsOut.from:type_name -> tricorn.StringNetworkAddress
	0,  // 8: tricorn.EventFundsOut.token:type_name -> tricorn.Address
	6,  // 9: tricorn.EventFundsOut.tx:type_name -> tricorn.TransactionInfo
	10, // 10: tricorn.ConnectorTokens.tokens:type_name -> tricorn.ConnectorTokens.ConnectorToken
	0,  // 11: tricorn.TokenOutRequest.token:type_name -> tricorn.Address
	0,  // 12: tricorn.TokenOutRequest.to:type_name -> tricorn.Address
	11, // 13: tricorn.TokenOutRequest.from:type_name -> tricorn.StringNetworkAddress
	0,  // 14: tricorn.ConnectorTokens.ConnectorToken.address:type_name -> tricorn.Address
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_connector_connector_proto_init() }
func file_connector_connector_proto_init() {
	if File_connector_connector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connector_connector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventFundsIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventFundsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectorTokens); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenOutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenOutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_connector_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectorTokens_ConnectorToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_connector_connector_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_connector_connector_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Event_FundsIn)(nil),
		(*Event_FundsOut)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connector_connector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connector_connector_proto_goTypes,
		DependencyIndexes: file_connector_connector_proto_depIdxs,
		MessageInfos:      file_connector_connector_proto_msgTypes,
	}.Build()
	File_connector_connector_proto = out.File
	file_connector_connector_proto_rawDesc = nil
	file_connector_connector_proto_goTypes = nil
	file_connector_connector_proto_depIdxs = nil
}
