// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: bridge-signer/bridge-signer.proto

package pb_bridge_signer

import (
	context "context"
	signer "github.com/BoostyLabs/golden-gate-communication/go-gen/signer"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BridgeSignerClient is the client API for BridgeSigner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BridgeSignerClient interface {
	// Return signed data for specific network.
	Sign(ctx context.Context, in *signer.SignRequest, opts ...grpc.CallOption) (*signer.Signature, error)
	// Return public key for specific network.
	PublicKey(ctx context.Context, in *signer.PublicKeyRequest, opts ...grpc.CallOption) (*signer.PublicKeyResponse, error)
}

type bridgeSignerClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeSignerClient(cc grpc.ClientConnInterface) BridgeSignerClient {
	return &bridgeSignerClient{cc}
}

func (c *bridgeSignerClient) Sign(ctx context.Context, in *signer.SignRequest, opts ...grpc.CallOption) (*signer.Signature, error) {
	out := new(signer.Signature)
	err := c.cc.Invoke(ctx, "/tricorn.BridgeSigner/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeSignerClient) PublicKey(ctx context.Context, in *signer.PublicKeyRequest, opts ...grpc.CallOption) (*signer.PublicKeyResponse, error) {
	out := new(signer.PublicKeyResponse)
	err := c.cc.Invoke(ctx, "/tricorn.BridgeSigner/PublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeSignerServer is the server API for BridgeSigner service.
// All implementations should embed UnimplementedBridgeSignerServer
// for forward compatibility
type BridgeSignerServer interface {
	// Return signed data for specific network.
	Sign(context.Context, *signer.SignRequest) (*signer.Signature, error)
	// Return public key for specific network.
	PublicKey(context.Context, *signer.PublicKeyRequest) (*signer.PublicKeyResponse, error)
}

// UnimplementedBridgeSignerServer should be embedded to have forward compatible implementations.
type UnimplementedBridgeSignerServer struct {
}

func (UnimplementedBridgeSignerServer) Sign(context.Context, *signer.SignRequest) (*signer.Signature, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedBridgeSignerServer) PublicKey(context.Context, *signer.PublicKeyRequest) (*signer.PublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicKey not implemented")
}

// UnsafeBridgeSignerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeSignerServer will
// result in compilation errors.
type UnsafeBridgeSignerServer interface {
	mustEmbedUnimplementedBridgeSignerServer()
}

func RegisterBridgeSignerServer(s grpc.ServiceRegistrar, srv BridgeSignerServer) {
	s.RegisterService(&BridgeSigner_ServiceDesc, srv)
}

func _BridgeSigner_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(signer.SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeSignerServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tricorn.BridgeSigner/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeSignerServer).Sign(ctx, req.(*signer.SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeSigner_PublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(signer.PublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeSignerServer).PublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tricorn.BridgeSigner/PublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeSignerServer).PublicKey(ctx, req.(*signer.PublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BridgeSigner_ServiceDesc is the grpc.ServiceDesc for BridgeSigner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeSigner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tricorn.BridgeSigner",
	HandlerType: (*BridgeSignerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _BridgeSigner_Sign_Handler,
		},
		{
			MethodName: "PublicKey",
			Handler:    _BridgeSigner_PublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge-signer/bridge-signer.proto",
}
