// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: transfers/transfers.proto

package pb_transfers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferResponse_Status int32

const (
	TransferResponse_STATUS_UNSPECIFIED TransferResponse_Status = 0
	TransferResponse_STATUS_CONFIRMING  TransferResponse_Status = 1
	TransferResponse_STATUS_CANCELLED   TransferResponse_Status = 2
	TransferResponse_STATUS_FINISHED    TransferResponse_Status = 3
	TransferResponse_STATUS_WAITING     TransferResponse_Status = 4
)

// Enum value maps for TransferResponse_Status.
var (
	TransferResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_CONFIRMING",
		2: "STATUS_CANCELLED",
		3: "STATUS_FINISHED",
		4: "STATUS_WAITING",
	}
	TransferResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_CONFIRMING":  1,
		"STATUS_CANCELLED":   2,
		"STATUS_FINISHED":    3,
		"STATUS_WAITING":     4,
	}
)

func (x TransferResponse_Status) Enum() *TransferResponse_Status {
	p := new(TransferResponse_Status)
	*p = x
	return p
}

func (x TransferResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_transfers_transfers_proto_enumTypes[0].Descriptor()
}

func (TransferResponse_Status) Type() protoreflect.EnumType {
	return &file_transfers_transfers_proto_enumTypes[0]
}

func (x TransferResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferResponse_Status.Descriptor instead.
func (TransferResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{3, 0}
}

type StringNetworkAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkName string `protobuf:"bytes,1,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	Address     string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *StringNetworkAddress) Reset() {
	*x = StringNetworkAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringNetworkAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringNetworkAddress) ProtoMessage() {}

func (x *StringNetworkAddress) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringNetworkAddress.ProtoReflect.Descriptor instead.
func (*StringNetworkAddress) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{0}
}

func (x *StringNetworkAddress) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *StringNetworkAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type StringTxHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkName string `protobuf:"bytes,1,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	Hash        string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *StringTxHash) Reset() {
	*x = StringTxHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringTxHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTxHash) ProtoMessage() {}

func (x *StringTxHash) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTxHash.ProtoReflect.Descriptor instead.
func (*StringTxHash) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{1}
}

func (x *StringTxHash) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *StringTxHash) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type TransferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash *StringTxHash `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{2}
}

func (x *TransferRequest) GetTxHash() *StringTxHash {
	if x != nil {
		return x.TxHash
	}
	return nil
}

type TransferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statuses []*TransferResponse_Transfer `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{3}
}

func (x *TransferResponse) GetStatuses() []*TransferResponse_Transfer {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type EstimateTransferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderNetwork    string `protobuf:"bytes,1,opt,name=sender_network,json=senderNetwork,proto3" json:"sender_network,omitempty"`
	RecipientNetwork string `protobuf:"bytes,2,opt,name=recipient_network,json=recipientNetwork,proto3" json:"recipient_network,omitempty"`
	TokenId          uint32 `protobuf:"varint,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Amount           string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *EstimateTransferRequest) Reset() {
	*x = EstimateTransferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateTransferRequest) ProtoMessage() {}

func (x *EstimateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateTransferRequest.ProtoReflect.Descriptor instead.
func (*EstimateTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{4}
}

func (x *EstimateTransferRequest) GetSenderNetwork() string {
	if x != nil {
		return x.SenderNetwork
	}
	return ""
}

func (x *EstimateTransferRequest) GetRecipientNetwork() string {
	if x != nil {
		return x.RecipientNetwork
	}
	return ""
}

func (x *EstimateTransferRequest) GetTokenId() uint32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *EstimateTransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type EstimateTransferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fee                   string `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	FeePercentage         string `protobuf:"bytes,2,opt,name=feePercentage,proto3" json:"feePercentage,omitempty"`
	EstimatedConfirmation uint32 `protobuf:"varint,3,opt,name=estimatedConfirmation,proto3" json:"estimatedConfirmation,omitempty"`
}

func (x *EstimateTransferResponse) Reset() {
	*x = EstimateTransferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateTransferResponse) ProtoMessage() {}

func (x *EstimateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateTransferResponse.ProtoReflect.Descriptor instead.
func (*EstimateTransferResponse) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{5}
}

func (x *EstimateTransferResponse) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *EstimateTransferResponse) GetFeePercentage() string {
	if x != nil {
		return x.FeePercentage
	}
	return ""
}

func (x *EstimateTransferResponse) GetEstimatedConfirmation() uint32 {
	if x != nil {
		return x.EstimatedConfirmation
	}
	return 0
}

type TransferHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset        uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	UserSignature []byte `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	NetworkId     uint32 `protobuf:"varint,4,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// optional for ETH, mandatory for Casper
	PublicKey []byte `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3,oneof" json:"public_key,omitempty"`
}

func (x *TransferHistoryRequest) Reset() {
	*x = TransferHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHistoryRequest) ProtoMessage() {}

func (x *TransferHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHistoryRequest.ProtoReflect.Descriptor instead.
func (*TransferHistoryRequest) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{6}
}

func (x *TransferHistoryRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TransferHistoryRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TransferHistoryRequest) GetUserSignature() []byte {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *TransferHistoryRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *TransferHistoryRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type TransferHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Statuses  []*TransferResponse_Transfer `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	TotalSize uint64                       `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
}

func (x *TransferHistoryResponse) Reset() {
	*x = TransferHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferHistoryResponse) ProtoMessage() {}

func (x *TransferHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferHistoryResponse.ProtoReflect.Descriptor instead.
func (*TransferHistoryResponse) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{7}
}

func (x *TransferHistoryResponse) GetStatuses() []*TransferResponse_Transfer {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *TransferHistoryResponse) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type BridgeInSignatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender      *StringNetworkAddress `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	TokenId     uint32                `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Amount      string                `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Destination *StringNetworkAddress `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *BridgeInSignatureRequest) Reset() {
	*x = BridgeInSignatureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeInSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeInSignatureRequest) ProtoMessage() {}

func (x *BridgeInSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeInSignatureRequest.ProtoReflect.Descriptor instead.
func (*BridgeInSignatureRequest) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{8}
}

func (x *BridgeInSignatureRequest) GetSender() *StringNetworkAddress {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *BridgeInSignatureRequest) GetTokenId() uint32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *BridgeInSignatureRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BridgeInSignatureRequest) GetDestination() *StringNetworkAddress {
	if x != nil {
		return x.Destination
	}
	return nil
}

type BridgeInSignatureWithNonceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender        []byte                `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Token         []byte                `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Nonce         uint64                `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Amount        string                `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Destination   *StringNetworkAddress `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	GasCommission string                `protobuf:"bytes,6,opt,name=gas_commission,json=gasCommission,proto3" json:"gas_commission,omitempty"`
}

func (x *BridgeInSignatureWithNonceRequest) Reset() {
	*x = BridgeInSignatureWithNonceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeInSignatureWithNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeInSignatureWithNonceRequest) ProtoMessage() {}

func (x *BridgeInSignatureWithNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeInSignatureWithNonceRequest.ProtoReflect.Descriptor instead.
func (*BridgeInSignatureWithNonceRequest) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{9}
}

func (x *BridgeInSignatureWithNonceRequest) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *BridgeInSignatureWithNonceRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *BridgeInSignatureWithNonceRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *BridgeInSignatureWithNonceRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BridgeInSignatureWithNonceRequest) GetDestination() *StringNetworkAddress {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *BridgeInSignatureWithNonceRequest) GetGasCommission() string {
	if x != nil {
		return x.GasCommission
	}
	return ""
}

type BridgeInSignatureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token         []byte                `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Amount        string                `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	GasCommission string                `protobuf:"bytes,3,opt,name=gas_commission,json=gasCommission,proto3" json:"gas_commission,omitempty"`
	Destination   *StringNetworkAddress `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Deadline      string                `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Nonce         uint64                `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *BridgeInSignatureResponse) Reset() {
	*x = BridgeInSignatureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeInSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeInSignatureResponse) ProtoMessage() {}

func (x *BridgeInSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeInSignatureResponse.ProtoReflect.Descriptor instead.
func (*BridgeInSignatureResponse) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{10}
}

func (x *BridgeInSignatureResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *BridgeInSignatureResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BridgeInSignatureResponse) GetGasCommission() string {
	if x != nil {
		return x.GasCommission
	}
	return ""
}

func (x *BridgeInSignatureResponse) GetDestination() *StringNetworkAddress {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *BridgeInSignatureResponse) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *BridgeInSignatureResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *BridgeInSignatureResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CancelTransferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransferId uint64 `protobuf:"varint,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Signature  []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	NetworkId  uint32 `protobuf:"varint,3,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// optional for ETH, mandatory for Casper
	PublicKey []byte `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3,oneof" json:"public_key,omitempty"`
}

func (x *CancelTransferRequest) Reset() {
	*x = CancelTransferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferRequest) ProtoMessage() {}

func (x *CancelTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferRequest.ProtoReflect.Descriptor instead.
func (*CancelTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{11}
}

func (x *CancelTransferRequest) GetTransferId() uint64 {
	if x != nil {
		return x.TransferId
	}
	return 0
}

func (x *CancelTransferRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CancelTransferRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *CancelTransferRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type CancelTransferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Nonce      uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature  []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Token      []byte `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Recipient  []byte `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Commission string `protobuf:"bytes,6,opt,name=commission,proto3" json:"commission,omitempty"`
	Amount     string `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *CancelTransferResponse) Reset() {
	*x = CancelTransferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferResponse) ProtoMessage() {}

func (x *CancelTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferResponse.ProtoReflect.Descriptor instead.
func (*CancelTransferResponse) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{12}
}

func (x *CancelTransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelTransferResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *CancelTransferResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CancelTransferResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CancelTransferResponse) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *CancelTransferResponse) GetCommission() string {
	if x != nil {
		return x.Commission
	}
	return ""
}

func (x *CancelTransferResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type CancelSignatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce      uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Token      []byte `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Recipient  []byte `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Commission string `protobuf:"bytes,6,opt,name=commission,proto3" json:"commission,omitempty"`
	Amount     string `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *CancelSignatureRequest) Reset() {
	*x = CancelSignatureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSignatureRequest) ProtoMessage() {}

func (x *CancelSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSignatureRequest.ProtoReflect.Descriptor instead.
func (*CancelSignatureRequest) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{13}
}

func (x *CancelSignatureRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *CancelSignatureRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CancelSignatureRequest) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *CancelSignatureRequest) GetCommission() string {
	if x != nil {
		return x.Commission
	}
	return ""
}

func (x *CancelSignatureRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type CancelSignatureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *CancelSignatureResponse) Reset() {
	*x = CancelSignatureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSignatureResponse) ProtoMessage() {}

func (x *CancelSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSignatureResponse.ProtoReflect.Descriptor instead.
func (*CancelSignatureResponse) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{14}
}

func (x *CancelSignatureResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TransferResponse_Transfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount       string                  `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Sender       *StringNetworkAddress   `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient    *StringNetworkAddress   `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Status       TransferResponse_Status `protobuf:"varint,5,opt,name=status,proto3,enum=golden_gate.TransferResponse_Status" json:"status,omitempty"`
	TriggeringTx *StringTxHash           `protobuf:"bytes,6,opt,name=triggering_tx,json=triggeringTx,proto3" json:"triggering_tx,omitempty"`
	OutboundTx   *StringTxHash           `protobuf:"bytes,7,opt,name=outbound_tx,json=outboundTx,proto3,oneof" json:"outbound_tx,omitempty"`
	CreatedAt    *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *TransferResponse_Transfer) Reset() {
	*x = TransferResponse_Transfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_transfers_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferResponse_Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse_Transfer) ProtoMessage() {}

func (x *TransferResponse_Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_transfers_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse_Transfer.ProtoReflect.Descriptor instead.
func (*TransferResponse_Transfer) Descriptor() ([]byte, []int) {
	return file_transfers_transfers_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TransferResponse_Transfer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferResponse_Transfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferResponse_Transfer) GetSender() *StringNetworkAddress {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *TransferResponse_Transfer) GetRecipient() *StringNetworkAddress {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *TransferResponse_Transfer) GetStatus() TransferResponse_Status {
	if x != nil {
		return x.Status
	}
	return TransferResponse_STATUS_UNSPECIFIED
}

func (x *TransferResponse_Transfer) GetTriggeringTx() *StringTxHash {
	if x != nil {
		return x.TriggeringTx
	}
	return nil
}

func (x *TransferResponse_Transfer) GetOutboundTx() *StringTxHash {
	if x != nil {
		return x.OutboundTx
	}
	return nil
}

func (x *TransferResponse_Transfer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_transfers_transfers_proto protoreflect.FileDescriptor

var file_transfers_transfers_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x6f, 0x6c,
	0x64, 0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x14, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x45,
	0x0a, 0x0c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x21,
	0x0a, 0x0c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x45, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6c, 0x64,
	0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x22, 0x89, 0x05, 0x0a,
	0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x42, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74,
	0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x08, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x65, 0x73, 0x1a, 0xb8, 0x03, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x6f, 0x6c,
	0x64, 0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65,
	0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x09, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f,
	0x67, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x3e, 0x0a, 0x0d, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x69,
	0x6e, 0x67, 0x5f, 0x74, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f,
	0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x52, 0x0c, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x69,
	0x6e, 0x67, 0x54, 0x78, 0x12, 0x3f, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x5f, 0x74, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6c, 0x64,
	0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x48, 0x00, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x54, 0x78, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x74, 0x78,
	0x22, 0x76, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4e,
	0x46, 0x49, 0x52, 0x4d, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x57,
	0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x22, 0xa0, 0x01, 0x0a, 0x17, 0x45, 0x73, 0x74,
	0x69, 0x6d, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x2b, 0x0a, 0x11, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x18,
	0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x65,
	0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x66, 0x65, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x34, 0x0a, 0x15, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x15, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xbf, 0x01, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x25, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x22, 0x7c, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x67,
	0x61, 0x74, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x08, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xcd, 0x01, 0x0a, 0x18, 0x42, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x49, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74,
	0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x43, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f,
	0x67, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xeb, 0x01, 0x0a, 0x21, 0x42, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x49, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x43, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a,
	0x0e, 0x67, 0x61, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x61, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x85, 0x02, 0x0a, 0x19, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x49,
	0x6e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x25, 0x0a, 0x0e, 0x67, 0x61, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x61, 0x73, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67,
	0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xa8, 0x01, 0x0a,
	0x15, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x22, 0xd0, 0x01, 0x0a, 0x16, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9a, 0x01, 0x0a, 0x16, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x17, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x42, 0x5c, 0x5a, 0x5a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42,
	0x6f, 0x6f, 0x73, 0x74, 0x79, 0x4c, 0x61, 0x62, 0x73, 0x2f, 0x63, 0x61, 0x73, 0x70, 0x65, 0x72,
	0x2d, 0x65, 0x74, 0x68, 0x2d, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2f, 0x62, 0x6f, 0x6f, 0x73,
	0x74, 0x79, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x73, 0x3b, 0x70, 0x62, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transfers_transfers_proto_rawDescOnce sync.Once
	file_transfers_transfers_proto_rawDescData = file_transfers_transfers_proto_rawDesc
)

func file_transfers_transfers_proto_rawDescGZIP() []byte {
	file_transfers_transfers_proto_rawDescOnce.Do(func() {
		file_transfers_transfers_proto_rawDescData = protoimpl.X.CompressGZIP(file_transfers_transfers_proto_rawDescData)
	})
	return file_transfers_transfers_proto_rawDescData
}

var file_transfers_transfers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transfers_transfers_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_transfers_transfers_proto_goTypes = []interface{}{
	(TransferResponse_Status)(0),              // 0: golden_gate.TransferResponse.Status
	(*StringNetworkAddress)(nil),              // 1: golden_gate.StringNetworkAddress
	(*StringTxHash)(nil),                      // 2: golden_gate.StringTxHash
	(*TransferRequest)(nil),                   // 3: golden_gate.TransferRequest
	(*TransferResponse)(nil),                  // 4: golden_gate.TransferResponse
	(*EstimateTransferRequest)(nil),           // 5: golden_gate.EstimateTransferRequest
	(*EstimateTransferResponse)(nil),          // 6: golden_gate.EstimateTransferResponse
	(*TransferHistoryRequest)(nil),            // 7: golden_gate.TransferHistoryRequest
	(*TransferHistoryResponse)(nil),           // 8: golden_gate.TransferHistoryResponse
	(*BridgeInSignatureRequest)(nil),          // 9: golden_gate.BridgeInSignatureRequest
	(*BridgeInSignatureWithNonceRequest)(nil), // 10: golden_gate.BridgeInSignatureWithNonceRequest
	(*BridgeInSignatureResponse)(nil),         // 11: golden_gate.BridgeInSignatureResponse
	(*CancelTransferRequest)(nil),             // 12: golden_gate.CancelTransferRequest
	(*CancelTransferResponse)(nil),            // 13: golden_gate.CancelTransferResponse
	(*CancelSignatureRequest)(nil),            // 14: golden_gate.CancelSignatureRequest
	(*CancelSignatureResponse)(nil),           // 15: golden_gate.CancelSignatureResponse
	(*TransferResponse_Transfer)(nil),         // 16: golden_gate.TransferResponse.Transfer
	(*timestamppb.Timestamp)(nil),             // 17: google.protobuf.Timestamp
}
var file_transfers_transfers_proto_depIdxs = []int32{
	2,  // 0: golden_gate.TransferRequest.tx_hash:type_name -> golden_gate.StringTxHash
	16, // 1: golden_gate.TransferResponse.statuses:type_name -> golden_gate.TransferResponse.Transfer
	16, // 2: golden_gate.TransferHistoryResponse.statuses:type_name -> golden_gate.TransferResponse.Transfer
	1,  // 3: golden_gate.BridgeInSignatureRequest.sender:type_name -> golden_gate.StringNetworkAddress
	1,  // 4: golden_gate.BridgeInSignatureRequest.destination:type_name -> golden_gate.StringNetworkAddress
	1,  // 5: golden_gate.BridgeInSignatureWithNonceRequest.destination:type_name -> golden_gate.StringNetworkAddress
	1,  // 6: golden_gate.BridgeInSignatureResponse.destination:type_name -> golden_gate.StringNetworkAddress
	1,  // 7: golden_gate.TransferResponse.Transfer.sender:type_name -> golden_gate.StringNetworkAddress
	1,  // 8: golden_gate.TransferResponse.Transfer.recipient:type_name -> golden_gate.StringNetworkAddress
	0,  // 9: golden_gate.TransferResponse.Transfer.status:type_name -> golden_gate.TransferResponse.Status
	2,  // 10: golden_gate.TransferResponse.Transfer.triggering_tx:type_name -> golden_gate.StringTxHash
	2,  // 11: golden_gate.TransferResponse.Transfer.outbound_tx:type_name -> golden_gate.StringTxHash
	17, // 12: golden_gate.TransferResponse.Transfer.created_at:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_transfers_transfers_proto_init() }
func file_transfers_transfers_proto_init() {
	if File_transfers_transfers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transfers_transfers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringNetworkAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringTxHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstimateTransferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstimateTransferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeInSignatureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeInSignatureWithNonceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeInSignatureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTransferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTransferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelSignatureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelSignatureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_transfers_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferResponse_Transfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_transfers_transfers_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_transfers_transfers_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_transfers_transfers_proto_msgTypes[15].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transfers_transfers_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transfers_transfers_proto_goTypes,
		DependencyIndexes: file_transfers_transfers_proto_depIdxs,
		EnumInfos:         file_transfers_transfers_proto_enumTypes,
		MessageInfos:      file_transfers_transfers_proto_msgTypes,
	}.Build()
	File_transfers_transfers_proto = out.File
	file_transfers_transfers_proto_rawDesc = nil
	file_transfers_transfers_proto_goTypes = nil
	file_transfers_transfers_proto_depIdxs = nil
}
